app/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),

    path('customers_list', views.customers_list, name='customers_list'),
    path('create_customer', views.create_customer, name='create_customer'),
    path('edit_customer/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.user_logout_view, name='logout'),
    # path('companies/<int:customer_id>/', views.companies_list, name='customer_companies'),

    # path('error-500/', views.error_500, name='error_500'),
    # path('pace/', views.pace, name='pace'),
    # path('blank-page/', views.blank_page, name='blank_page'),
    # path('starter-page/', views.starter_page, name='starter_page'),
    # # Authentication
    # path('accounts/register/', views.register, name='register'),
    # path('accounts/login/', views.UserLoginView.as_view(), name='login'),
    # path('accounts/logout/', views.user_logout_view, name='logout'),
    # path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    # path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
    #     template_name='accounts/password_change_done.html'
    # ), name="password_change_done"),
    # path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    # path('accounts/password-reset-confirm/<uidb64>/<token>/',
    #      views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
    #     template_name='accounts/password_reset_done.html'
    # ), name='password_reset_done'),
    # path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
    #     template_name='accounts/password_reset_complete.html'
    # ), name='password_reset_complete'),
]

app/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('', include('scheduler.urls')),
    path('admin/', admin.site.urls),
]

app/website/urls.py
from django.urls import path
from . import views

app_name = 'public'
urlpatterns = [
    path('', views.index, name='index'),
]

app/accounts/models.py
from django.db import models
from tenant_users.tenants.models import TenantBase, UserProfile
from django_tenants.models import DomainMixin


class User(UserProfile):
    name = models.CharField(max_length=100)


class Customer(TenantBase):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, unique=True)
    # default true, schema will be automatically created and synced when it is saved
    # auto_create_schema = True

    def __str__(self):
        return self.name


class Domain(DomainMixin):
    pass

app/website/models.py
from django.db import models

# Create your models here.

app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ValidationError
from django.forms import models

from .models import User, Customer


class LoginForm(AuthenticationForm):
    # You can customize the form fields or add additional fields if needed
    # class Meta:
    #     model = User
    #     fields = ['email', 'password']
    username = UsernameField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email'
    }))
    password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password'
    }))

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class TenantForm(forms.Form):
    user_email = forms.EmailField()
    code = forms.CharField(max_length=50)
    name = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError("Passwords do not match. Please enter matching passwords.")

        return cleaned_data
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

app/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from tenant_users.tenants.models import ExistsError
from tenant_users.tenants.tasks import provision_tenant

from .forms import CustomerForm, LoginForm, TenantForm
from .models import Customer, User, Domain


# Create your views here.

def get_rag_status_counts():
    green_count = 2
    yellow_count = 4
    red_count = 5
    return green_count, yellow_count, red_count


@login_required
def home(request):
    customers = Customer.objects.all()
    green_count, yellow_count, red_count = get_rag_status_counts()
    print(Domain.objects.all())
    context = {
        'user_obs': '',
        'customers': customers,
        'green_count': green_count,
        'yellow_count': yellow_count,
        'red_count': red_count,

        'parent': '',
        'segment': 'dashboard'
    }
    return render(request, 'home.html', context)


# Create your views here.

@login_required
def customers_list(request):
    customers = Customer.objects.all()
    return render(request, 'customers_list.html', {'customers': customers, 'segment': 'accounts:customers_list'})


@login_required
def create_customer(request):
    try:
        if request.method == 'POST':
            form = TenantForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                # Create user
                user = User.objects.create_user(email=data['user_email'], password=data['password'], is_staff=True)
                # Provision tenant
                provision_tenant(data['name'], data['code'], data['user_email'], tenant_extra_data={"code": data['code']})
                # Redirect or render success page
                return redirect('accounts:customers_list')
        else:
            form = TenantForm()
    except ExistsError as e:
        # Handle the specific ExistsError exception
        messages.error(request, 'User already exists. Please use a different email address.')

    except Exception as e:
        # Log the exception for debugging purposes
        print(f"An error occurred: {str(e)}")
        # Display a generic error message
        messages.error(request, 'An error occurred while processing your request. Please try again later.')

    return render(request, 'customer_form.html', {'form': form})


@login_required
def edit_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('accounts:customers_list')  # Redirect to customers list
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'customer_form.html', {'form': form, 'customer': customer})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('accounts:home')  # Redirect to home or any desired URL after login
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout_view(request):
    logout(request)
    return redirect('accounts:login')

app/website/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

app/accounts/templates/accounts/forgot-password.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Forgot Password {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <b>Test Django Tenants</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

      <form method="post">
        {% csrf_token %}
        
        {% for field in form %}
        <div class="input-group mb-3">
          {{field}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <p class="mt-3 mb-1">
        <a href="{% url 'login' %}">Login</a>
      </p>
<!--

      <p class="mb-0">
        <a href="{% url 'registration_v1' %}" class="text-center">Register a new membership</a>
      </p>
    -->
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/login.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Log in {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <b>Test Django Tenants</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start your session</p>

      <form method="post">
        {% csrf_token %}

        {% if form.non_field_errors %}
          {% for error in form.non_field_errors  %}
            <small class="text-danger mb-3">{{ error }}</small>
          {% endfor %}
        {% endif %}

        {% for field in form %}
        <div class="input-group mb-3">
          {{field}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas {% if field.name == 'username' %} fa-user {% else %}  fa-lock {% endif %}"></span>
            </div>
          </div>
        </div>
        <small class="text-danger">{{ field.errors }}</small>
        {% endfor %}
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
{% endblock %}

app/accounts/templates/accounts/password_change.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Change Password {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <b>Test Django Tenants</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You are only one step a way from your new password, change your password now.</p>

      <form method="post">
        {% csrf_token %}

        {% for field in form %}
        <div class="input-group mb-3">
          {{field}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <small class="text-danger">{{ field.errors }}</small>
        {% endfor %}
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Change password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="/scheduler/static">Cancel</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/password_change_done.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Reset Complete {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <b>Test Django Tenants</b>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Your password has been changed successfully.</p>
      <a href="/scheduler/static">Go to dashboard</a>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/password_reset_complete.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Reset Complete {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <a href="/scheduler/static"><b>Test Django Tenants </b>Admin</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Your password has been changed successfully and you can login again.</p>

      <p class="mt-3 mb-1">
        <a href="{% url 'login' %}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/password_reset_done.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Email sent {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <a href="/scheduler/static"><b>Test Django Tenants</b> Admin</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">An email has been sent to your email address. Please click the link and reset your password.</p>

      <p class="mt-3 mb-1">
        <a href="{% url 'login' %}">Login</a>
      </p>
      <p class="mb-0">
        <a href="{% url 'register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/recover-password.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Recover Password {% endblock title %}

{% block bodyclass %} login-page {% endblock bodyclass %}

{% block content %}
<div class="login-box">
  <div class="login-logo">
    <a href="/scheduler/static"><b>Scheduler</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">You are only one step a way from your new password, recover your password now.</p>

      <form method="post">
        {% csrf_token %}

        {% for field in form %}
        <div class="input-group mb-3">
          {{field}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <small class="text-danger">{{ field.errors }}</small>
        {% endfor %}
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Change password</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{% url 'login' %}">Login</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>

{% endblock %}

app/accounts/templates/accounts/register.html
{% extends 'layouts/auth_base.html' %}

{% block title %} Registration Page {% endblock title %}

{% block bodyclass %} register-page {% endblock bodyclass %}

{% block content %}
<div class="register-box">
  <div class="register-logo">
    <a href="/scheduler/static"><b>Test Django Tenants </b> Registation</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form method="post">
        {% csrf_token %}

        {% for field in form %}
        <div class="input-group mb-3">
          {{field}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas {% if field.name == 'username' %} fa-user {% else %} {% if field.name == 'email' %} fa-envelope {% else %} fa-lock {% endif %} {% endif %}"></span>
            </div>
          </div>
        </div>
        <small class="text-danger">{{ field.errors }}</small>
        {% endfor %}
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <!--
      <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div>
      -->

      <p class="mt-4 mb-2 text-center">
        Have an account? <a href="{% url 'login' %}" class="text-center">Sign IN</a>
      </p>
      
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
{% endblock content %}

app/accounts/templates/customers_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Customers List {% endblock title %}
{% block extrastyle %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrastyle %}
{% block bodyclass %} hold-transition sidebar-mini {% endblock bodyclass %}
{% block content %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Customers List</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <a href="{% url 'accounts:create_customer' %}" class="btn btn-primary">Create New
                                Customer</a>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-body">
                            <table class="table table-hover" id="customer_table">
                                <thead>
                                <tr>

                                    <th>Name</th>
                                    <th>Customer Code</th>
                                    <th>&nbsp;</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if customers is not True %}
                                    {% for customer in customers %}
                                        <tr>

                                            <td>{{ customer.name }}</td>
                                            <td>{{ customer.code }}</td>

                                            <td>
                                                 <a class="btn btn-sm btn-warning"
                                                           href="{% url 'accounts:edit_customer' customer_id=customer.pk %}">Edit Customer</a>


                                            </td>

                                        </tr>
                                    {% endfor %}
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}
{% block extra_scripts %}

    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script>
        $(function () {
            $('#customer_table').DataTable();
        });
    </script>
{% endblock extra_scripts %}

app/accounts/templates/includes/footer.html
{% load static %}

<footer class="main-footer">
    <strong>&copy; Test Django Tenants</strong>
</footer>

app/accounts/templates/includes/menu-list.html
{% load i18n static admin_adminlte %}

<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->

    {% admin_get_menu as app_list %}
    {% if app_list %}
        {% for app in app_list %}
            {% if app.has_perms and not app.pinned %}
                <li class="nav-item {% if 'dashboard' in parent %} menu-open {% endif %}">
                    <a class="nav-link {% if app_label != app.label and app.url not in request.path|urlencode %} {% if app.url == request.path %} active expanded {% else %} collapsed {% endif %}{% endif %}"
                       data-bs-toggle="collapse" data-bs-target="#submenu-{{ app.app_label }}" href="{{ app.url }}">
                        <i class="nav-icon {{ app.icon }}"></i>
                        <p>
                            {{ app.label|slice:10 }}{% if app.label|length > 10 %}..{% endif %}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    {% if app.models %}
                        <ul class="nav nav-treeview">
                            {% for model in app.models %}
                                {% if model.url %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if 'bootstrap-tables' in segment or model.url in request.path|urlencode %} active {% endif %}"
                                           href="{{ model.url }}">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>{{ model.label }}</p>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="nav-item">{{ model.label }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'accounts:home' %}" class="nav-link {% if 'dashboard' in segment %}active{% endif %}">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:customers_list' %}"
               class="nav-link {% if 'accounts:customers_list' in segment %}active{% endif %}">
                <i class="nav-icon fas fa-th"></i>
                <p>
                    Customers List
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:create_customer' %}"
               class="nav-link {% if 'accounts:create_customer' in segment %}active{% endif %}">
                <i class="nav-icon fas fa-edit"></i>
                <p>
                    Create New Customer
                </p>
            </a>
        </li>
    {% endif %}

    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'accounts:logout' %}" class="nav-link">
                <i class="fa fa-sign-out-alt nav-icon"></i>
                <p>Logout</p>
            </a>
        </li>
    {% else %}
        <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link">
                <i class="fa fa-sign-in-alt nav-icon"></i>
                <p>Login</p>
            </a>
        </li>
    {% endif %}
</ul>

app/accounts/templates/includes/navigation-light.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'public:index' %}" class="nav-link">Home</a>
        </li>
{#        <li class="nav-item d-none d-sm-inline-block">#}
{#            <a href="#" class="nav-link">Contact</a>#}
{#        </li>#}
        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'admin:password_change' %}" class="nav-link">Change Password</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
                </li>
            {% else %}
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'password_change' %}" class="nav-link">Change Password</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                </li>
            {% endif %}
        {% else %}
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'login' %}" class="nav-link">Sign In</a>
            </li>
        {% endif %}
    </ul>

    <!-- Right navbar links Navbar Search
        <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
            <form class="form-inline">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                  <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>
   -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item  d-none d-sm-inline-block">
         <a href="#" class="nav-link"> {% if request.user.is_authenticated %}
                {{ request.user.username }}
            {% endif %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <!--
     <li class="nav-item">
       <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
         <i class="fas fa-th-large"></i>
       </a>
     </li> -->
    </ul>
</nav>
<!-- /.navbar -->

app/accounts/templates/includes/scripts.html
{% load static %}

<script src="{% static 'plugins/htmx/htmx.min.js' %}" defer></script>

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
{#<script src="{% static 'dist/js/demo.js' %}"></script>#}

app/accounts/templates/layouts/auth_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Test Django Tenants | {% block title %}{% endblock title %}</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition {% block bodyclass %}{% endblock bodyclass %}">

  {% block content %}{% endblock content %}

  {% block scripts %}
    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  {% endblock scripts %}

</body>
</html>